### ISSUE TITLE
Ultrastaffchat reloading plugin/config gives out error

### ISSUE THREAD

**Issue by Tydium** [Phoenix616/Snap#11]
#### SNAP Build #11 (From jenkins. Should be latest)
Full log from boot to end: https://pastebin.com/nkdmRQxH
 
 
#### Environment description
Running on the latest Velocity 1.1.5 on Ubuntu 20.04 with a docker container (pterodactyl). I have 3 other main plugins in there which is practically just geyser/floodgate and luckperms and thats it.
 
#### Full Log

```
Full log from boot to end: https://pastebin.com/nkdmRQxH
```

#### What other programs/plugins are you running?
The server plugins only have Geyser, Floodgate, and Luckperms (and obviously snap) 
I have no other plugins on snap but ultrastaffchat 

#### What is happening?
When I try to do "/ultrastaffchat reload" it gives a long error. The reload only reloads the config.

#### What did you expect to happen?
No reload error

#### Additional context

nothing really. pretty straight forward.

**Comment by Phoenix616** [comment]
Seeing as this is an obfuscated premium resource and there is no way to see what it is doing there it's pretty much impossible to fix that. The author would need to provide some information regarding what the plugin is doing there.

**Comment by Tydium** [comment]
Hey we can close this if you want. I no longer use the plugin. I never used the premium version btw. Only the free version.

**Comment by Phoenix616** [comment]
Not sure why I thought it was premium, probably because your version seems to be obfuscated and there is no reason to do that for a free and open source one? Anyways, just leave it open for others to see and me to eventually take a look what's going on there when I find the time.

**Comment by Phoenix616** [comment]
Not an issue with Snap, this is literally a bug in their code:
![](https://phoenix616.dev/📷/glgmVYcs.png)

Please test with the latest version of the plugin and see if the issue persists.
