### ISSUE TITLE
bungeecontrol-red background continuous washing frequency

### ISSUE THREAD

**Issue by BearLeonLight** [Phoenix616/Snap#21]
#### Is your feature request related to a problem? Please describe.

Due to incomplete inversion of the control, error messages and warning messages always appear.
【https://bitbucket.org/kangarko/bungeecontrol-red/src/master/】
#### Describe the solution you'd like

Error messages and warning messages sent by using this plug-in can be intercepted, or compatibility can be improved.

#### Describe alternatives you've considered

I tried to develop this new Velocity support, but she didn't have time to study the Velocity code, so he said that he was willing to open source it to others to help develop it. (https://github.com/kangarko/ChatControl-Red/issues/724)

#### Additional context

![image](https://user-images.githubusercontent.com/52900334/143689848-dd2cf025-217b-478c-8ded-6668cd2214e5.png)

**Comment by Phoenix616** [comment]
They are using non-api, internel classes which cannot be supported. Either get them to fix that abuse or use a plugin with native Velocity support or one that doesn't care about the proxy (e.g. SpaceChat comes to mind as a cross server chat plugin)

**Comment by kangarko** [comment]
My plugin is open source, maybe you can have a look at what specifically needs to be done to make this work:

https://bitbucket.org/kangarko/bungeecontrol-red/src/master/

We have a Velocity fork work in progress.

**Comment by Phoenix616** [comment]
> My plugin is open source, maybe you can have a look at what specifically needs to be done to make this work:
> 
> https://bitbucket.org/kangarko/bungeecontrol-red/src/master/

1. Your plugin is not open source (the readme clearly states that it is proprietary)
2. All you need to do is depend on `bungee-api`, not the internal proxy jar. (I assume due to whatever [this artifact](https://github.com/kangarko/BungeeFoundation/blob/master/pom.xml#L37-L41) is in BungeeFoundation, no idea why you are not using the official artifact in the first place tbh)

**Comment by kangarko** [comment]
Thanks, I'll have a look in my spare time.

**Comment by kangarko** [comment]
The reason we use the server and not the api is that we use the "ServerConnection" class instead "Connection" due to missing methods. Should I just check for ProxiedPlayer and cast Connection to that instead?

**Comment by BearLeonLight** [comment]
Can I take the test? (Currently considering switching to Velocity and not using BC)
In addition, I'm still in the basic stage of development, I originally wanted to try to change it, but I couldn't understand it in the world, and there were some APIs that I couldn't get.

**Comment by kangarko** [comment]
Yes! I will ship this with BungeeControl Red which is bundled in ChatControl Red. You can find our link to the plugin by googling for ChatControl Red for example.
