### ISSUE TITLE
FastLogin

### ISSUE THREAD

**Issue by mirkocerati** [Phoenix616/Snap#3]
Hi there. FastLogin doesn't work.
https://pastebin.com/KgCiegeS

Same thing if I change to MySQL instead of SQLite.
I'm using the latest build of FastLoginBungee (https://ci.codemc.io/job/Games647/job/FastLogin/).

**Comment by Phoenix616** [comment]
Hm, looks like the BungeeCord-api artifact doesn't specify SQLite/MySQL drivers but includes it via the proxy artifact? I'm not sure if I should include those directly seeing as it's easily possible to just provide those via the classpath.

**Comment by mirkocerati** [comment]
I'm not a Java Developer so I really don't know what you're talking about, lol.
Is it something that can be fixed?

**Comment by Phoenix616** [comment]
That has nothing to do with developing Java, adding libraries to the classpath is part of starting and running a java application.

**Comment by mirkocerati** [comment]
So, is there a way to fix this issue?

**Comment by Phoenix616** [comment]
Yes, either provide the required library in your classpath, shade it into the plugin jar itself or wait until someone has looked into this and maybe included a fix.

**Comment by astei** [comment]
Velocity doesn't ship with any JDBC drivers by default, primarily because there's no need for us to do so.

@Phoenix616 It may be worth it to shade in the same version of SQLite and MySQL Connector/J as BungeeCord to reduce any "shock".

**Comment by Phoenix616** [comment]
Added some more of the stuff BungeeCord/Waterfall provide. They do not include SQLite so I don't think Snap should either (and as the error already correctly identifies one would have to use MySQL on Bungee.)
