### ISSUE TITLE
Use @Getter instead of void getters

### ISSUE THREAD

**Issue by seailz** [Phoenix616/Snap#37]
#### Is your feature request related to a problem? Please describe.
not really a problem

#### Describe the solution you'd like
Instead of using default void getters as seen here
```java

    public PluginConfig getConfig() {
        return config;
    }

    public ProxyServer getProxy() {
        return proxy;
    }

    public Logger getLogger() {
        return logger;
    }

    public Path getDataFolder() {
        return dataFolder;
    }

    public SnapBungeeAdapter getBungeeAdapter() {
        return bungeeAdapter;
    }

    public Map<UUID, SnapPlayer> getPlayers() {
        return players;
    }

    public Map<String, SnapPlayer> getPlayerNames() {
        return playerNames;
    }
``` 
,
use `@Getter` from lombok. 10x easier

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by Phoenix616** [comment]
Lombok reduces the verbosity of the code as well as complicate the promect setup (and potentially evenbreaks builds) so adding it just for getters makes no sense.
