### ISSUE TITLE
MySQL plugins

### ISSUE THREAD

**Issue by WarnDangerous** [Phoenix616/Snap#5]
#### Used Version
Dev version 9 (so with mysql-connector)
 
 
#### Config

 ```Default config
 ```
 
#### Environment description
MySQL doesn't work on DynamicBungeeAuth
 
 
#### Full Log

https://pastebin.com/43Q1GadZ
(I replaced the ip with some XXXX)

**Comment by Phoenix616** [comment]
Please provide your full log or at least the used plugin version and a link to the plugin's source or at least information about which driver it is trying to load.

**Comment by kubo6472** [comment]
https://www.spigotmc.org/resources/dynamicbungeeauth-premium-command-semi-premium-system-sessions.27480/
@Phoenix616 

@WarnDangerous 
1. Don't crack plugins
2. The dev has an official support server
3. FILL OUT THE TEMPLATE PROPERLY

**Comment by WarnDangerous** [comment]
I bought the plugin so it’s not cracked, I removed snap and dynamicbungeeauth because now I use online mode.

so this ticket can be closed.

**Comment by kubo6472** [comment]
> 
> 
> I bought the plugin so it’s not cracked, I removed snap and dynamicbungeeauth because now I use online mode.
> 
> so this ticket can be closed.

aight, your call...
